---
permalink: /admin/config.yml
---

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - {{ site.data.admin.collections.homework | jsonify }}
  - {{ site.data.admin.collections.lessons | jsonify }}
  - {{ site.data.admin.collections.projects | jsonify }}
  - {{ site.data.admin.collections.resources | jsonify }}
  - {{ site.data.admin.collections.topics | jsonify }}
  - {{ site.data.admin.collections.units | jsonify }}
